name: Build all versions and publish to NPM
on: push
jobs:
  build:
    name: Build ${{ matrix.build-group }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            arch: x64
            build-group: linux-x64
          - os: macos-13
            arch: x64
            build-group: darwin-universal
          - os: windows-2019
            arch: x86
            build-group: win32-x86
          - os: windows-2019
            arch: x64
            build-group: win32-x64
    env:
      BUILD_GROUP: ${{ matrix.build-group }}
    steps:
      - uses: actions/checkout@v3
      - name: Install OS Dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get install libxtst-dev libpng++-dev gcc g++ -y
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          architecture: ${{ matrix.arch }}
      - run: npm install
      - name: Prebuildify
        run: npm run prebuild-$BUILD_GROUP
        shell: bash
      - uses: actions/upload-artifact@v2
        with:
          name: prebuilds
          path: prebuilds/
  publish:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
      - name: Install OS Dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get install libxtst-dev libpng++-dev gcc g++ -y
      - name: Install dependencies
        run: npm ci
      - uses: actions/download-artifact@v2
        with:
          name: prebuilds
          path: prebuilds
      - name: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
