name: Build all versions and publish to NPM
on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
jobs:
  Publish-NPM:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: npx ci
      - name: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
  BuildAll:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        arch: [ia32, x64]
        nodeBuild: [16.13.0, 14.18.1]
        electBuild: [15.3.2, 14.2.1]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'
    - name: Install OS Dependencies
      if: ${{ runner.os == 'Linux' }}
      run: sudo apt-get install libxtst-dev libpng++-dev
    - name: Install dependencies
      run: npx ci
    - name: Prebuild Node
      run: npx prebuild -t ${{ matrix.nodeBuild }} --arch=${{ matrix.arch }} -u ${{ secrets.GITHUB_TOKEN }}
    - name: Prebuild Latest Electron
      run: npx prebuild -t ${{ matrix.electBuild }} -r electron --arch=${{ matrix.arch }} -u ${{ secrets.GITHUB_TOKEN }}
