name: Build all versions
on:
  push:
    branches-ignore:
      - master
jobs:
  BuildAll:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        arch: [ia32, x64]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'
    - name: Install OS Dependencies
      if: ${{ runner.os == 'Linux' && matrix.arch == 'x64' }}
      run: sudo apt-get install libxtst-dev libpng++-dev gcc-multilib g++-multilib -y
    - name: Install OS Dependencies (32-bit)
      if: ${{ runner.os == 'Linux' && matrix.arch == 'ia32' }}
      run: sudo dpkg --add-architecture i386 && sudo apt-get update && sudo apt-get install libxtst-dev:i386 libpng++-dev:i386 gcc-multilib g++-multilib -y
    - name: Fix Symbolic Link for Lib (32-bit)
      if: ${{ runner.os == 'Linux' && matrix.arch == 'ia32' }}
      run: sudo ln -s /usr/lib32/libXtst.so.6 /usr/lib/libXtst.so
    - name: Install dependencies
      run: npm ci
    - name: Prebuild All
      run: npx prebuild --all --runtime napi --arch=${{ matrix.arch }}
